// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/chat.tsx";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/switcher.tsx";
import * as $$0 from "./islands/Chat.tsx";
import * as $$1 from "./islands/ChatForm.tsx";
import * as $$2 from "./islands/ChatList.tsx";
import * as $$3 from "./islands/ChatTop.tsx";
import * as $$4 from "./islands/Container.tsx";
import * as $$5 from "./islands/Contents.tsx";
import * as $$6 from "./islands/Gallery.tsx";
import * as $$7 from "./islands/NowPlaying.tsx";
import * as $$8 from "./islands/PersonalityCard.tsx";
import * as $$9 from "./islands/ProgramCard.tsx";
import * as $$10 from "./islands/ProgramCardCompact.tsx";
import * as $$11 from "./islands/ProgramCards.tsx";
import * as $$12 from "./islands/Switcher.tsx";

const manifest = {
  routes: {
    "./routes/chat.tsx": $0,
    "./routes/index.tsx": $1,
    "./routes/switcher.tsx": $2,
  },
  islands: {
    "./islands/Chat.tsx": $$0,
    "./islands/ChatForm.tsx": $$1,
    "./islands/ChatList.tsx": $$2,
    "./islands/ChatTop.tsx": $$3,
    "./islands/Container.tsx": $$4,
    "./islands/Contents.tsx": $$5,
    "./islands/Gallery.tsx": $$6,
    "./islands/NowPlaying.tsx": $$7,
    "./islands/PersonalityCard.tsx": $$8,
    "./islands/ProgramCard.tsx": $$9,
    "./islands/ProgramCardCompact.tsx": $$10,
    "./islands/ProgramCards.tsx": $$11,
    "./islands/Switcher.tsx": $$12,
  },
  baseUrl: import.meta.url,
};

export default manifest;
