// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/chat.tsx";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/switcher.tsx";
import * as $$0 from "./islands/NowPlaying.tsx";
import * as $$1 from "./islands/PersonalityCard.tsx";
import * as $$2 from "./islands/ProgramCard.tsx";
import * as $$3 from "./islands/ProgramCardCompact.tsx";
import * as $$4 from "./islands/ProgramCards.tsx";
import * as $$5 from "./islands/Switcher.tsx";

const manifest = {
  routes: {
    "./routes/chat.tsx": $0,
    "./routes/index.tsx": $1,
    "./routes/switcher.tsx": $2,
  },
  islands: {
    "./islands/NowPlaying.tsx": $$0,
    "./islands/PersonalityCard.tsx": $$1,
    "./islands/ProgramCard.tsx": $$2,
    "./islands/ProgramCardCompact.tsx": $$3,
    "./islands/ProgramCards.tsx": $$4,
    "./islands/Switcher.tsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
