const iconNames = [
  "t-rex_3d",
  "crab_3d",
  "frog_3d",
  "spouting_whale_3d",
  "shark_3d",
  "monkey_face_3d",
  "dog_face_3d",
  "cat_face_3d",
  "unicorn_3d",
  "cow_face_3d",
  "pig_face_3d",
  "mouse_face_3d",
  "rabbit_face_3d",
  "bear_3d",
  "koala_3d",
  "panda_3d",
  "hatching_chick_3d",
  "penguin_3d",
  "duck_3d",
  "parrot_3d",
  "dragon_face_3d",
  "turtle_3d",
  "seal_3d",
  "dolphin_3d",
  "sauropod_3d",
  "snail_3d",
  "bug_3d",
  "fox_3d",
  "raccoon_3d",
  "lion_3d",
  "tiger_face_3d",
  "peacock_3d",
  "chicken_3d",
  "dodo_3d",
];

export default iconNames;
