import { Program } from "../types/Program.ts";

const programs: Program[] = [
  {
    id: 1,
    iconName: "radio",
    title: "オープニング",
    personalityLastNames: ["酒井", "鈴木", "田中", "中村", "西村", "林"],
    overview: "まずはここから！パーソナリティの自己紹介と最近あった出来事をお届けします。",
    playtime: 7,
    day: 1,
  },
  {
    id: 10,
    iconName: "detective",
    title: "M2への質問",
    personalityLastNames: ["酒井", "鈴木", "田中", "中村", "西村", "林"],
    overview:
      "みなさんの質問やお悩みにM2が全員で答えます！世の中の課題を解決するのが吉野研。あなたの悩みくらい、M2がスパッと解決してみせましょう。",
    playtime: 28,
    day: 1,
  },
  {
    id: 7,
    iconName: "face_with_rolling_eyes",
    title: "こいつ変やなって思ったエピソード",
    personalityLastNames: ["鈴木", "西村", "林"],
    overview: "吉野研には変人が多い！？この番組では、パーソナリティの3人が吉野研の人たちの変なエピソードを語る。はずだった...",
    playtime: 37,
    day: 1,
  },
  {
    id: 15,
    iconName: "shushing_face",
    title: "この際だから言っておきたいこと",
    personalityLastNames: ["鈴木", "田中", "中村"],
    overview: "先輩・同期・後輩に言いたいけど言えなかったこと。この機会にぶちまけちゃいます！",
    playtime: 12,
    day: 1,
  },
  {
    id: 8,
    iconName: "dress",
    title: "シス工ファッション委員会",
    personalityLastNames: ["田中", "中村"],
    overview:
      "M2の紅ニ点が、みんなのお便りを読みながらお届けするフリートーク！タイトル回収はできるのか、全く違う方向に転がっていくのか。予測不可能！",
    playtime: 30,
    day: 1,
  },
  {
    id: 11,
    iconName: "church",
    title: "吉野研裁判 ~M2に懺悔を~",
    personalityLastNames: ["酒井", "鈴木", "田中", "中村", "西村", "林"],
    overview: "今まで隠してきたけど心が痛むことありますよね？この機会に告白しましょう。我々があなたの罪を洗い流し（もとい断罪し）ます。",
    playtime: 11,
    day: 1,
  },
  {
    id: 19,
    iconName: "musical_note",
    title: "林のベスト曲3選",
    personalityLastNames: ["林"],
    overview: "M2林が厳選した3曲を紹介します！",
    playtime: 16,
    day: 1,
  },
  {
    id: 17,
    iconName: "heart_with_arrow",
    title: "漢の恋バナ",
    personalityLastNames: ["酒井", "林"],
    overview: "M2男児による漢のための漢の恋バナ！恋愛経験豊富（？）な二人の仰天エピソードが炸裂？！",
    playtime: 36,
    day: 1,
  },
  {
    id: 23,
    iconName: "musical_note",
    title: "鈴木のベスト曲3選",
    personalityLastNames: ["鈴木"],
    overview: "M2鈴木が厳選した3曲を紹介します！",
    playtime: 17,
    day: 1,
  },
  {
    id: 22,
    iconName: "musical_note",
    title: "田中のベスト曲3選",
    personalityLastNames: ["田中"],
    overview: "M2田中が厳選した3曲を紹介します。",
    playtime: 18,
    day: 1,
  },
  {
    id: 12,
    iconName: "astonished_face",
    title: "M2が知らなそうなこと",
    personalityLastNames: ["酒井", "鈴木", "田中", "中村", "西村", "林"],
    overview: "みなさんから寄せられた、M2が知らなそうな豆知識・エピソードをを紹介します！M2だけど、何でもは知らないわ。知ってることだけ。",
    playtime: 18,
    day: 2,
  },
  {
    id: 20,
    iconName: "musical_note",
    title: "西村のベスト曲3選",
    personalityLastNames: ["西村"],
    overview: "M2西村が厳選した3曲を紹介します。",
    playtime: 30,
    day: 2,
  },
  {
    id: 2,
    iconName: "water_pistol",
    title: "Mr.林のマシンガントーク ~ジョジョ編~",
    personalityLastNames: ["林", "酒井"],
    overview:
      "マシンガントークでおなじみのMr.林が、今一番熱いコンテンツについて語る！第1弾となる「ジョジョ編」では、あなたをジョジョの世界に引き込みます。酒井のリアクションにも注目？",
    playtime: 21,
    day: 2,
  },
  {
    id: 18,
    iconName: "beer_mug",
    title: "鈴木・西村のほろよい雑談",
    personalityLastNames: ["鈴木", "西村"],
    overview:
      "吉野研で随一の「下戸」な二人が、ほんとにお酒を飲みながら雑談するだけの番組です。大量に届いたお便りをすべてさばききれるのか？それとも寝てしまうのか？最後まで必聴です。",
    playtime: 62,
    day: 2,
  },
  {
    id: 21,
    iconName: "musical_note",
    title: "中村のベスト曲3選",
    personalityLastNames: ["中村"],
    overview: "M2中村が厳選した3曲を紹介します！",
    playtime: 17,
    day: 2,
  },
  {
    id: 13,
    iconName: "crown",
    title: "吉野研〇〇ランキング",
    personalityLastNames: ["酒井", "鈴木", "田中", "中村", "西村", "林"],
    overview: "吉野研で一番〇〇な人は誰か！？みんなのお便りから意外な一面が明らかになるかも。あなたは名誉（？）を掴み取ることができるか。",
    playtime: 47,
    day: 3,
  },
  {
    id: 24,
    iconName: "musical_note",
    title: "酒井のベスト曲3選",
    personalityLastNames: ["酒井"],
    overview: "M2酒井が厳選した3曲を紹介します！",
    playtime: 16,
    day: 3,
  },
  {
    id: 6,
    iconName: "old_man",
    title: "みんなの10年後を語ろう",
    personalityLastNames: ["鈴木", "田中", "西村"],
    overview:
      "吉野研のみんなの10年後をテーマに、あることないことざっくばらんに語ります。浪人経験など、意外と共通点の多い3人のフリートークが聞けるのはここだけ！",
    playtime: 19,
    day: 3,
  },
  {
    id: 3,
    iconName: "water_pistol",
    title: "Mr.林のマシンガントーク ~マーベル編~",
    personalityLastNames: ["鈴木", "林", "田中"],
    overview: "マシンガントークでおなじみのMr.林が、今一番熱いコンテンツについて語る！ジョジョ編ですでにお腹いっぱいの方も必聴！",
    playtime: 19,
    day: 3,
  },
  {
    id: 5,
    iconName: "radio",
    title: "エンディング",
    personalityLastNames: ["酒井", "鈴木", "田中", "中村", "西村", "林"],
    overview: "終わりよければ全て良し！のはずが...",
    playtime: 10,
    day: 3,
  },
];

export default programs;
