import { Program } from "../types/Program.ts";

const programs: Program[] = [
  {
    id: 1,
    iconName: "radio",
    title: "オープニング",
    personalityLastNames: ["酒井", "鈴木", "田中", "中村", "西村", "林"],
    overview: "まずはここから！",
    playtime: 10,
  },
  {
    id: 2,
    iconName: "water_pistol",
    title: "Mr.林のマシンガントーク ~ジョジョ編~",
    personalityLastNames: ["林", "酒井"],
    overview:
      "マシンガントークでおなじみのMr.林が，今一番熱いコンテンツについて語る！第1弾となる「ジョジョ編」では，あなたをジョジョの世界に引き込みます．",
    playtime: 60,
  },

  {
    id: 3,
    iconName: "water_pistol",
    title: "Mr.林のマシンガントーク ~マーベル編~",
    personalityLastNames: ["鈴木", "林", "田中"],
    overview: "マシンガントークでおなじみのMr.林が，今一番熱いコンテンツについて語る！ジョジョ編ですでにお腹いっぱいの方も必聴！",
    playtime: 21,
  },
  {
    id: 4,
    iconName: "index_pointing_at_the_viewer",
    title: "このマイブームはあなたのだ！",
    personalityLastNames: ["鈴木", "林", "田中"],
    overview: "あなたのユニークなマイブームを教えて下さい．後輩を誰よりも理解しているM2ならあなたが誰か当てられる(はず)．",
    playtime: 21,
  },
  {
    id: 6,
    iconName: "old_man",
    title: "みんなの10年後を語ろう",
    personalityLastNames: ["鈴木", "田中", "西村"],
    overview:
      "吉野研のみんなの10年後をテーマに，あることないことざっくばらんに語ります．浪人経験など，意外と共通点の多い3人のフリートークが聞けるのはここだけ！",
    playtime: 21,
  },
  {
    id: 7,
    iconName: "face_with_rolling_eyes",
    title: "こいつ変やなって思ったエピソード",
    personalityLastNames: ["鈴木", "西村", "林"],
    overview: "吉野研には変人が多い！？この番組では，パーソナリティの3人が吉野研の人たちの変なエピソードを語る．はずだった...",
    playtime: 21,
  },
  {
    id: 8,
    iconName: "dress",
    title: "シス工ファッション委員会",
    personalityLastNames: ["田中", "中村"],
    overview:
      "M2の紅ニ点が，みんなのお便りを読みながらお届けするフリートーク！タイトル回収はできるのか，全く違う方向に転がっていくのか．予測可能！",
    playtime: 21,
  },
  {
    id: 9,
    iconName: "face_with_spiral_eyes",
    title: "吉野研で一番大変だったこと",
    personalityLastNames: ["田中", "中村", "西村"],
    overview:
      "M2だからこそわかる苦労がある？この番組では吉野研生活で大変だったことを振り返りながら，ざっくばらんなフリートークを展開します．地獄を見てきた者達だ．面構えが違う．",
    playtime: 21,
  },
  {
    id: 10,
    iconName: "detective",
    title: "お悩み相談",
    personalityLastNames: ["酒井", "鈴木", "田中", "中村", "西村", "林"],
    overview: "みなさんのお悩みにM2が答えます！世の中の課題を解決するのが吉野研．あなたの悩みくらい，M2がスパッと解決してみせましょう．",
    playtime: 21,
  },
  {
    id: 11,
    iconName: "church",
    title: "吉野研裁判 ~M2に懺悔を~",
    personalityLastNames: ["酒井", "鈴木", "田中", "中村", "西村", "林"],
    overview: "今まで隠してきたけど，心が痛むこと，ありますよね？この機会に告白しましょう．我々があなたの罪を洗い流します．",
    playtime: 21,
  },
  {
    id: 12,
    iconName: "astonished_face",
    title: "M2に「へぇ〜」と言わせたら勝ち",
    personalityLastNames: ["酒井", "鈴木", "田中", "中村", "西村", "林"],
    overview: "みなさんから寄せられた，M2が知らなそうな豆知識・エピソードをを紹介します！何でもは知らないわ．知ってることだけ．",
    playtime: 21,
  },
  {
    id: 13,
    iconName: "crown",
    title: "吉野研〇〇ランキング",
    personalityLastNames: ["酒井", "鈴木", "田中", "中村", "西村", "林"],
    overview: "吉野研で一番〇〇な人は誰か！？あなたは名誉（？）を掴み取ることができるか...",
    playtime: 21,
  },
  {
    id: 14,
    iconName: "broom",
    title: "田中さんPresents 吉野研雑務振り返りトーク",
    personalityLastNames: ["田中", "中村"],
    overview: "一部界隈では，吉野研で最も雑務をこなしていると言われている田中さん．そんな彼女がこれまでこなしてきた数々の仕事を振り返ります．",
    playtime: 21,
  },
  {
    id: 15,
    iconName: "shushing_face",
    title: "この際だから言っておきたいこと",
    personalityLastNames: ["鈴木", "田中", "中村"],
    overview: "先輩・同期・後輩に，言いたいけど言えなかったこと．この機会にぶちまけましょう！",
    playtime: 21,
  },
  {
    id: 16,
    iconName: "student",
    title: "大学(院)でやっておくべきこと",
    personalityLastNames: ["酒井", "田中", "西村"],
    overview: "卒業を間近に控えた3人が，大学(院)でやっておくべきことについて語ります！思い返すのは美しい思い出か．それとも後悔か...？",
    playtime: 21,
  },
  {
    id: 17,
    iconName: "heart_with_arrow",
    title: "漢の恋バナ",
    personalityLastNames: ["酒井", "林"],
    overview: "M2男児による漢の恋バナ！経験豊富な二人の恋愛エピソードが炸裂？！",
    playtime: 21,
  },
  {
    id: 18,
    iconName: "beer_mug",
    title: "鈴木・西村のほろよい雑談",
    personalityLastNames: ["鈴木", "西村"],
    overview:
      "吉野研でも随一の下戸である二人が，ほんとにお酒を飲みながら雑談するだけの番組です．大量に届いたお便りをすべてさばききれるのか？それとも寝てしまうのか？最後まで必聴です．",
    playtime: 21,
  },
  {
    id: 5,
    iconName: "radio",
    title: "エンディング",
    personalityLastNames: ["酒井", "鈴木", "田中", "中村", "西村", "林"],
    overview: "終わりよければ全て良し！",
    playtime: 10,
  },
];

export default programs;
